version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: >-
    choco install -y python2
    pip install pywin32
    C:\cygwin\setup-x86.exe    
build_script:
- cmd: >-
    python build_ffmpeg.py --target_arch x64 -pc

    python build_ffmpeg.py --target_arch ia32 -pc
artifacts:
- path: releases/*.zip
