version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: >-
    choco install -y python2
    
    pip install pywin32
    
    setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P yasm -P make -P diffutils -P pkg-config -P git
build_script:
- cmd: >-
    dir
    
    cd "C:\Program Files (x86)\Microsoft Visual Studio 15.9\VC"
    
    vcvarsall.bat [amd64, amd64_x86]
    
    dir C:\cygwin64\bin
    
    python build_ffmpeg.py --target_arch x64 -pc

    python build_ffmpeg.py --target_arch ia32 -pc
artifacts:
- path: releases/*.zip
